improved error handling

diff --git a/lsni b/lsni
--- a/lsni
+++ b/lsni
@@ -1,20 +1,26 @@
 #!/usr/bin/env sh
 
 if [ $# -eq 0 ]; then
-    echo "Usage: $0 DIRECTORY"
+    echo "Usage: $0 directory_name"
     exit 1
+fi
+
+if ! command -v bat &> /dev/null; then
+    RUNNER="cat"
+else
+    RUNNER="bat --decorations never --language markdown"
 fi
 
 DIR="$1"
 LOOKER="${DIR}/.lsinfo"
 
 if [ ! -d "$DIR" ]; then
-    echo "Directory $DIR does not exist"
+    echo "Error: directory '$DIR' does not exist"
     exit 1
 fi
 
 if [ -f "${LOOKER}" ]; then
-    bat --decorations never --language markdown $LOOKER
+    $RUNNER $LOOKER
     echo
 fi
 ls "$DIR"
